import Navbar from "../../../components/navbar.js";
export const metadata = {
  title: "Sahil Lala: Photos",
  description: "Generated by create next app",
};
export default function Photos() {
    return (
        <div>
          <Navbar />
        </div>
    );
  }