import Navbar from "../../components/navbar.js";
import App from "../../components/app.js";
export const metadata = {
  title: "Sahil Lala: Home",
  description: "Generated by create next app",
};
export default function Home() {

    return (
        <div >
          <Navbar />
          <App />
        </div>
    );
}
